services:
  uxplay:
    build: ./docker/uxplay
    container_name: uxplay-airplay
    network_mode: bridge
    ports:
      - "7000:7000/tcp"
      - "7000:7000/udp"
      - "7001:7001/tcp"
      - "7001:7001/udp"
      - "7100:7100/tcp"
      - "6000:6000/tcp"
      - "6001:6001/tcp"
    volumes:
      - ./frames:/frames:rw
    restart: unless-stopped
    environment:
      - DISPLAY=:0